CREATE TABLE LM_TEMPLIB(
    TEMPLIB_ID INTEGER NOT NULL AUTO_INCREMENT,
    TEMPLIB_NAME VARCHAR(300) NOT NULL,
    TEMPLIB_VERSION VARCHAR(50),
    TEMPLIB_FILE_NAME VARCHAR(500),
    TEMPLIB_TYPE VARCHAR(20),
    TEMPLIB_PARENT VARCHAR(300),
    TEMPLIB_VENDOR VARCHAR(200),
    TEMPLIB_DESCRIPTION VARCHAR(400),
    TEMPLIB_URL VARCHAR(300),
    TEMPLIB_LR_ID INT,

    PRIMARY KEY (TEMPLIB_ID),
    FOREIGN KEY (TEMPLIB_LR_ID) REFERENCES LM_LICENSEREQUEST(LR_ID),
	UNIQUE(TEMPLIB_NAME,TEMPLIB_VERSION,TEMPLIB_TYPE,TEMPLIB_LR_ID)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_TEMPCOMPONENT(
    TC_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TC_KEY VARCHAR(500) NOT NULL,
    TC_NAME VARCHAR(500),
    TC_TYPE VARCHAR(20),
    TC_VERSION VARCHAR(50),
    TC_VENDOR VARCHAR(200),
    TC_URL VARCHAR(300),
    TC_DESCRIPTION VARCHAR(400),
    TC_FILE_NAME VARCHAR(80),
    TC_LR_ID INT,

    FOREIGN KEY (TC_LR_ID) REFERENCES LM_LICENSEREQUEST(LR_ID),
    UNIQUE(TC_KEY,TC_LR_ID)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_COMPONENT_TEMPLIB(
       COMP_KEY VARCHAR(500),
       TEMPLIB_ID INTEGER,
       FOREIGN KEY (COMP_KEY) REFERENCES LM_COMPONENT (COMP_KEY),
       FOREIGN KEY (TEMPLIB_ID) REFERENCES LM_TEMPLIB (TEMPLIB_ID),
       UNIQUE(COMP_KEY,TEMPLIB_ID)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_TEMPLIB_LICENSE(
	TEMPLIB_ID INTEGER,
    LICENSE_KEY VARCHAR(50),
	FOREIGN KEY (TEMPLIB_ID) REFERENCES LM_TEMPLIB (TEMPLIB_ID),
	FOREIGN KEY (LICENSE_KEY) REFERENCES LM_LICENSE (LICENSE_KEY),
	UNIQUE(TEMPLIB_ID,LICENSE_KEY)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_TEMPLIB_PRODUCT(
       TEMPLIB_ID INTEGER,
       PRODUCT_ID INTEGER,
       FOREIGN KEY (TEMPLIB_ID) REFERENCES LM_TEMPLIB (TEMPLIB_ID),
       FOREIGN KEY (PRODUCT_ID) REFERENCES LM_PRODUCT (PRODUCT_ID),
	   UNIQUE(TEMPLIB_ID,PRODUCT_ID)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_TEMPCOMPONENT_LICENSE(
       TC_KEY VARCHAR(500),
       LICENSE_KEY VARCHAR(50),
       FOREIGN KEY (TC_KEY) REFERENCES LM_TEMPCOMPONENT (TC_KEY),
       FOREIGN KEY (LICENSE_KEY) REFERENCES LM_LICENSE (LICENSE_KEY),
       UNIQUE(TC_KEY,LICENSE_KEY)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

ALTER TABLE LM_REPOSITORY ADD COLUMN REPOSITORY_PRODUCT_AREA VARCHAR(200) DEFAULT NULL;