CREATE TABLE LM_LIBRARY_TEMP(
    TL_ID INTEGER NOT NULL AUTO_INCREMENT,
    TL_NAME VARCHAR(300) NOT NULL,
    TL_VERSION VARCHAR(50),
    TL_FILE_NAME VARCHAR(500),
    TL_TYPE VARCHAR(20),
    TL_PARENT VARCHAR(300),
    TL_VENDOR VARCHAR(200),
    TL_DESCRIPTION VARCHAR(400),
    TL_URL VARCHAR(300),
    TL_LR_ID INT,

    PRIMARY KEY (TL_ID),
    FOREIGN KEY (TL_LR_ID) REFERENCES LM_LICENSE_REQUEST(LR_ID),
	UNIQUE(TL_NAME,TL_VERSION,TL_TYPE,TL_LR_ID)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_COMPONENT_TEMP(
    TC_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TC_KEY VARCHAR(500) NOT NULL,
    TC_NAME VARCHAR(500),
    TC_TYPE VARCHAR(20),
    TC_VERSION VARCHAR(50),
    TC_VENDOR VARCHAR(200),
    TC_URL VARCHAR(300),
    TC_DESCRIPTION VARCHAR(400),
    TC_FILE_NAME VARCHAR(80),
    TC_LR_ID INT,

    FOREIGN KEY (TC_LR_ID) REFERENCES LM_LICENSE_REQUEST(LR_ID),
    UNIQUE(TC_KEY,TC_LR_ID)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_LICENSE_REQUEST (
    LR_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LR_REQUEST_BY VARCHAR(50),
    LR_STATE VARCHAR(10),
    LR_PRODUCT_ID INTEGER UNIQUE,
    FOREIGN KEY (LR_PRODUCT_ID) REFERENCES LM_PRODUCT (PRODUCT_ID)
);
--CREATE TABLE LM_COMPONENT_TEMPLIB(
--       COMP_KEY VARCHAR(500),
--       TL_ID INTEGER,
--       FOREIGN KEY (COMP_KEY) REFERENCES LM_COMPONENT (COMP_KEY),
--       FOREIGN KEY (TL_ID) REFERENCES LM_LIBRARY_TEMP (TL_ID),
--       UNIQUE(COMP_KEY,TL_ID)
--)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

--CREATE TABLE LM_TEMPLIB_LICENSE(
--	TL_ID INTEGER,
--    LICENSE_KEY VARCHAR(50),
--	FOREIGN KEY (TL_ID) REFERENCES LM_LIBRARY_TEMP (TL_ID),
--	FOREIGN KEY (LICENSE_KEY) REFERENCES LM_LICENSE (LICENSE_KEY),
--	UNIQUE(TL_ID,LICENSE_KEY)
--)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

--CREATE TABLE LM_TEMPLIB_PRODUCT(
--       TL_ID INTEGER,
--       PRODUCT_ID INTEGER,
--       FOREIGN KEY (TL_ID) REFERENCES LM_LIBRARY_TEMP (TL_ID),
--       FOREIGN KEY (PRODUCT_ID) REFERENCES LM_PRODUCT (PRODUCT_ID),
--	   UNIQUE(TL_ID,PRODUCT_ID)
--)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

--CREATE TABLE LM_TEMPCOMPONENT_LICENSE(
--       TC_KEY VARCHAR(500),
--       LICENSE_KEY VARCHAR(50),
--       FOREIGN KEY (TC_KEY) REFERENCES LM_COMPONENT_TEMP (TC_KEY),
--       FOREIGN KEY (LICENSE_KEY) REFERENCES LM_LICENSE (LICENSE_KEY),
--       UNIQUE(TC_KEY,LICENSE_KEY)
--)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;



--ALTER TABLE LM_REPOSITORY ADD COLUMN REPOSITORY_PRODUCT_AREA VARCHAR(200) DEFAULT NULL;