# database driver
driver: com.mysql.jdbc.Driver
#database url
url: jdbc:mysql://localhost:3306/licensegen
#username
userName: root
#password
password: Incorrect
#path to store file
path: /home/buddhik/Documents/MyWork/test/
#client origin
origin: http://localhost:8080
#default license id
licenseId: 31
#bpmn origin
bpmnOrigin: http://localhost:8080
#bpmn URL
bpmnUrl: https://localhost:9445/
#bpmn token
bpmnToken: Basic YWRtaW46YWRtaW4=
#email
emailAddress: webmisproject@gmail.com
#email password
emailPassword: ""
#smtp port
smtpPort: 25
#smtp host
smtpHost: smtp.gmail.com
#publicKey
publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvO8vWFWoxhLbdBLR0q4RpUbulGx4a202VrICWxsa7cGt/PDBd2W2WIZwtX4LdYktcYKBTBAjwD/efQP9b72ablQgyh7BQx/wHKYd7jxf9frlsS5BiYAlOB4c/kjuQgBJOXPn5TPkvI0uoUuVehpwoSrRZuLaRGRHuoSwTM9ENNeIyAJtY4QDLddRfefEM9Ecdp1zjgF6jIAHnJiB6AZZypdE704cWiB1MMu6TeWmqixtiW9V56G42tMPw+OiqesZmtNoaPJ9yQ0BMwAhBL9JkN4Oupgq3swRp2XoTOeBzsBiutuBO5IuBRvi/wsmyGwceAI9Co298zfnLIOJDYs+LQIDAQAB"