package org.wso2.internalapps.lm.thirdpartylibrary.common.sqlqueries;

public class MySQLQueries {

    public final String ALTER_LM_LIBRARY_GAD = "ALTER TABLE LM_LIBRARY ADD (" +
            "LIB_ARTIFACT_ID VARCHAR(300) NULL, " +
            "LIB_GROUP_ID VARCHAR(300) NULL, " +
            "LIB_DATE DATE NULL, " +
            "LIB_LATEST_VERSION VARCHAR(300) NULL, " +
            "LIB_LATEST_DATE DATE NULL);";

    public final String SELECT_LM_LIBRARY_ALL = "SELECT * from LM_LIBRARY";
    public final String SELECT_LM_LIBRARY_ALL_GAVD_NOTNULL = "SELECT * from LM_LIBRARY WHERE LIB_ARTIFACT_ID IS NOT NULL OR LIB_ARTIFACT_ID <> ''";
    public final String SELECT_LM_LIBRARY_GA_NULL = "SELECT * from LM_LIBRARY WHERE LIB_ARTIFACT_ID IS NULL OR LIB_ARTIFACT_ID='' OR LIB_GROUP_ID IS NULL order by LIB_ID";
    public final String SELECT_LM_LIBRARY_GA_D_NULL = "SELECT * from LM_LIBRARY WHERE LIB_ARTIFACT_ID IS NOT NULL AND LIB_GROUP_ID IS NOT NULL AND LIB_DATE IS NULL order by LIB_ID";

    public final String UPDATE_LM_LIBRARY_LATEST_DATE = "UPDATE LM_LIBRARY SET LIB_LATEST_VERSION = ?, LIB_LATEST_DATE = ? WHERE LIB_ID=?";
    public final String UPDATE_LM_LIBRARY_LATEST = "UPDATE LM_LIBRARY SET LIB_LATEST_VERSION = ? WHERE LIB_ID=?";
    public final String UPDATE_LM_LIBRARY_GA = "UPDATE LM_LIBRARY SET LIB_ARTIFACT_ID = ?, LIB_GROUP_ID = ? WHERE LIB_ID=?";
    public final String UPDATE_LM_LIBRARY_GAD = "UPDATE LM_LIBRARY SET LIB_ARTIFACT_ID = ?, LIB_GROUP_ID = ?, LIB_DATE = ? WHERE LIB_ID=?";
    public final String UPDATE_LM_LIBRARY_DATE = "UPDATE LM_LIBRARY SET LIB_DATE = ? WHERE LIB_ID=?";
}
